version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=fintech_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ="America/Sao_Paulo"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

  fintech_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./log:/var/log
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  pgdata:
  redisdata:
