export enum REGISTRY_TYPE {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  ADD_BALANCE = 'ADD_BALANCE',

  BEGIN_TRANSACTION = 'BEGIN_TRANSACTION',
  PROCESSING_MERCHANT_TRANSFER = 'PROCESSING_MERCHANT_TRANSFER',
  PROCESSING_COMMON_TRANSFER = 'PROCESSING_COMMON_TRANSFER',
  ENDING_TRANSACTION = 'ENDING_TRANSACTION',

  ERROR = 'ERROR',
}
